---
resources:
- name: source
  type: git
  source:
    uri: https://gitlower.onefiserv.net/esf/esfclientbase.git
    ignore_paths: 
      - README.md
      - .gitignore
      - CICD/metadata/*
      - CICD/pipeline.yml
    branch: master
    username: ((git.username))
    password: ((git.password))

- name: docker-image
  type: docker-image
  source:
    username: ((harbor.username))
    password: ((harbor.password))
    repository: harbor.fiserv.com:443/esf/esf-client-base

- name: bump
  type: semver
  source:
    driver: git
    branch: master
    uri: https://gitlower.onefiserv.net/esf/esfclientbase.git
    file: CICD/metadata/tag
    username: ((git.username))
    password: ((git.password))

jobs:
- name: build-docker-image-tagged
  serial: true
  plan:      
  - get: source
    trigger: true
  - put: bump
    params:
      bump: patch
  - put: docker-image
    params:
      build: source
      tag: bump/version

- name: build-docker-image-latest
  serial: true
  plan:
  - get: source
    passed: [build-docker-image-tagged]
    trigger: true
  - put: docker-image
    params:
      build: source

- name: update-cluster-repo
  plan:
  - get: source
    trigger: true
    passed: [build-docker-image-tagged]
  - get: bump
  - task: update-deployment
    file: source/tasks/update-deployment.yml
    params:
      DEPLOYMENT: planespotter-frontend.yml
      IMAGE_NAME: harbor.gcp.59s.io:443/59s/planespotter-frontend
  - put: cluster-repo
    params:
      repository: out

- name: config-cluster
  serial: true
  plan:
  - get: source
    trigger: true
  - task: provision-cluster
    file: cluster-state/ci/tasks/provision-cluster.yml
    params:
      PKS_CLUSTER: ((PKS_CLUSTER))
      PKS_USER: ((PKS_USER))
      PKS_PASSWORD: ((PKS_PASSWORD))
      PKS_URL: ((PKS_URL))