---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
  - name: esf-repo

outputs:
  - name: config-files

run:
  path: sh
  args:
  - -exc
  - |
    env
    sed -e "s/##var-to-be-replaced1##/$CONFIG_VAR1/g" -e "s/##var-to-be-replaced2##/$CONFIG_VAR2/g" esf-repo/config-templates/var-config-template.xml > config-files/var-config.xml
    cat config-files/var-config.xml