---
resources:
- name: source
  type: git
  source:
    uri: ((git.url.source))
    ignore_paths: 
      - README.md
      - .gitignore
      - cicd/metadata/*
      - cicd/pipeline.yml
    branch: master
    username: ((git.username))
    password: ((git.password))

- name: deployment-source
  type: git
  source:
    uri: ((git.url.deployment-source))
    ignore_paths: 
      - README.md
      - .gitignore
    branch: master
    username: ((git.username))
    password: ((git.password))

- name: docker-image
  type: docker-image
  source:
    username: ((harbor.username))
    password: ((harbor.password))
    repository: ((harbor.url))

- name: bump
  type: semver
  source:
    driver: git
    branch: master
    uri: ((git.url.source))
    file: cicd/metadata/tag
    username: ((git.username))
    password: ((git.password))

- name: send-email
  type: email
  source:
    from: your@email.com

jobs:
- name: build-docker-image-tagged
  serial: true
  plan:      
  - get: source
    trigger: true
  - put: bump
    params:
      bump: patch
  - put: docker-image
    params:
      build: source
      tag: bump/version

- name: build-docker-image-latest
  serial: true
  plan:
  - get: source
    trigger: true
  - put: docker-image
    params:
      build: source

- name: update-deployment-version
  plan:
  - get: source
    trigger: true
    passed: [build-docker-image-tagged]
  - get: deployment-source
  - get: bump
  - task: update-deployment
    file: source/cicd/tasks/update-deployment.yml
    params:
      DEPLOYMENT: deployment.yml
      IMAGE_NAME: ((harbor.url))
  - put: deployment-source
    params:
      repository: out
      merge: true

- name: deploy-pks-cluster
  serial: true
  plan:
  - get: source
    trigger: true
    passed: [update-deployment-version]
  - get: deployment-source
  - task: provision-cluster
    file: source/cicd/tasks/provision-cluster.yml
    params:
      PKS_CLUSTER: ((pks.cluster))
      PKS_USER: ((pks.username))
      PKS_PASSWORD: ((pks.password))
      PKS_URL: ((pks.url))
  - put: send-email
      params:
        to: [ 'to@email.com' ]
        subject_text: "PKS deployment complete"
        body_text: "Your content goes here."

  on_failure:
      put: send-email
      params:
        to: [ 'to@email.com' ]
        subject: ./email-text/email-subject-failure.txt