---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: yosepk/esf-image

run:
  path: sh
  args:
  - -exc
  - |
    env
    apk add --update curl
    cd /esf
    npm start &
    sleep 10 
    curl http://127.0.0.1:5000/configs/var-config.xml > output.txt
    cat output.txt | grep HELLO ; echo $?
    
