---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: yosepk/pks-worker
params:
  PKS_CLUSTER: ((pks.cluster))
  PKS_USER: ((pks.username))
  PKS_PASSWORD: ((pks.password))
  PKS_URL: ((pks.url))
inputs:
- name: source
run:
  path: source/cicd/tasks/provision-cluster.sh