---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine:latest
params:
  DEPLOYMENT:
  IMAGE_NAME:
inputs:
- name: source
- name: bump
outputs:
- name: out
run:
  path: source/cicd/tasks/update-deployment.sh